custom:
  appSync:
    name: ${self:service}-${opt:stage}
    authenticationType: API_KEY
    apiKeys:
      - name: graphql-${opt:stage}
        description: 'GraphQL {STAGE_NAME_CAPITALIZED} API_KEY'
        expiresAfter: 90d
    mappingTemplates:
      ${file(./config/envs/${opt:stage}/serverless-appsync-mapping-templates-section.generated.yml):mappingTemplates}
    serviceRole: "AppSyncServiceRole"
    schema: models/graphql/schema.graphql
    dataSources:
      ${file(./config/envs/${opt:stage}/serverless-appsync-datasource.generated.yml):dataSources}