custom:
  appSync:
    name: ${self:service}-${opt:stage}
    authenticationType: AWS_LAMBDA
    lambdaAuthorizerConfig:
      functionName: authLambda
      lambdaFunctionArn:
        "Fn::GetAtt": [ authLambdaLambdaFunction, Arn]
    mappingTemplates:
      ${file(./config/envs/${opt:stage}/serverless-appsync-mapping-templates-section.generated.yml):mappingTemplates}
    serviceRole: ${param:APPSYNC_SERVICE_ROLE}
    schema: models/graphql/schema.graphql
    dataSources:
      ${file(./config/envs/${opt:stage}/serverless-appsync-datasource.generated.yml):dataSources}